export enum ErrorCode {
	ERR_ENTROPY_LENGTH = "ERR_ENTROPY_LENGTH",
	ERR_INVALID_MNEMONIC_FORMAT = "ERR_INVALID_MNEMONIC_FORMAT",
	ERR_INVALID_WORD_COUNT = "ERR_INVALID_WORD_COUNT",
	ERR_WORD_NOT_IN_LIST = "ERR_WORD_NOT_IN_LIST",
	ERR_CHECKSUM_MISMATCH = "ERR_CHECKSUM_MISMATCH",
	ERR_PBKDF2_FAILURE = "ERR_PBKDF2_FAILURE",
}

export const MNEMONIC_VALIDATION_ERROR_PRIORITY = [
	ErrorCode.ERR_INVALID_MNEMONIC_FORMAT,
	ErrorCode.ERR_INVALID_WORD_COUNT,
	ErrorCode.ERR_WORD_NOT_IN_LIST,
	ErrorCode.ERR_CHECKSUM_MISMATCH,
] as const;

export const MNEMONIC_TO_SEED_ERROR_PRIORITY = [
	ErrorCode.ERR_INVALID_MNEMONIC_FORMAT,
	ErrorCode.ERR_PBKDF2_FAILURE,
] as const;
